server:
  port: 8080


spring:
  application:
    name: weather-service
 
 
app:
  weather:
    api:
      key: 22b9cf77aed55571f98c3189f1e003c3
      weatherurl: http://api.openweathermap.org/data/2.5/weather?zip={zip},{country}&APPID={key}
      forecasturl: http://api.openweathermap.org/data/2.5/forecast?zip={zip},{country}&APPID={key}